double circle_unit_area ( );
double *circle_unit_sample ( int n, int *seed );
double cos_power_int ( double a, double b, int n );
double p01_exact ( );
double *p01_f ( int n, double x[] );
void p01_param ( char *action, int *e );
int p01_param_get ( );
void p01_param_set ( int e );
double p02_exact ( );
double *p02_f ( int n, double x[] );
void p02_param ( char *action, int *e );
int p02_param_get ( );
void p02_param_set ( int e );
double p03_exact ( );
double *p03_f ( int n, double x[] );
double r8vec_sum ( int n, double a[] );
double *r8vec_uniform_01_new ( int n, int *seed );
double sin_power_int ( double a, double b, int n );
void timestamp ( );