double p00_f ( int problem, double x );
double p00_f1 ( int problem, double x );
double p00_f1_dif ( int problem, double x );
double p00_f2 ( int problem, double x );
double p00_f2_dif ( int problem, double x );
double p00_fmin ( double *a, double *b, int problem, double tol );
void p00_interval ( int problem, double *a, double *b );
int p00_problem_num ( );
double p00_sol ( int problem );
double p00_start ( int problem );
void p00_title ( int problem, char *title );
double p01_f ( double x );
double p01_f1 ( double x );
double p01_f2 ( double x );
void p01_interval ( double *a, double *b );
double p01_sol ( );
double p01_start ( );
void p01_title ( char *title );
double p02_f ( double x );
double p02_f1 ( double x );
double p02_f2 ( double x );
void p02_interval ( double *a, double *b );
double p02_sol ( );
double p02_start ( );
void p02_title ( char *title );
double p03_f ( double x );
double p03_f1 ( double x );
double p03_f2 ( double x );
void p03_interval ( double *a, double *b );
double p03_sol ( );
double p03_start ( );
void p03_title ( char *title );
double p04_f ( double x );
double p04_f1 ( double x );
double p04_f2 ( double x );
void p04_interval ( double *a, double *b );
double p04_sol ( );
double p04_start ( );
void p04_title ( char *title );
double p05_f ( double x );
double p05_f1 ( double x );
double p05_f2 ( double x );
void p05_interval ( double *a, double *b );
double p05_sol ( );
double p05_start ( );
void p05_title ( char *title );
double p06_f ( double x );
double p06_f1 ( double x );
double p06_f2 ( double x );
void p06_interval ( double *a, double *b );
double p06_sol ( );
double p06_start ( );
void p06_title ( char *title );
double p07_f ( double x );
double p07_f1 ( double x );
double p07_f2 ( double x );
void p07_interval ( double *a, double *b );
double p07_sol ( );
double p07_start ( );
void p07_title ( char *title );
double p08_f ( double x );
double p08_f1 ( double x );
double p08_f2 ( double x );
void p08_interval ( double *a, double *b );
double p08_sol ( );
double p08_start ( );
void p08_title ( char *title );
double p09_f ( double x );
double p09_f1 ( double x );
double p09_f2 ( double x );
void p09_interval ( double *a, double *b );
double p09_sol ( );
double p09_start ( );
void p09_title ( char *title );
double p10_f ( double x );
double p10_f1 ( double x );
double p10_f2 ( double x );
void p10_interval ( double *a, double *b );
double p10_sol ( );
double p10_start ( );
void p10_title ( char *title );
double p11_f ( double x );
double p11_f1 ( double x );
double p11_f2 ( double x );
void p11_interval ( double *a, double *b );
double p11_sol ( );
double p11_start ( );
void p11_title ( char *title );
double p12_f ( double x );
double p12_f1 ( double x );
double p12_f2 ( double x );
void p12_interval ( double *a, double *b );
double p12_sol ( );
double p12_start ( );
void p12_title ( char *title );
double p13_f ( double x );
double p13_f1 ( double x );
double p13_f2 ( double x );
void p13_interval ( double *a, double *b );
double p13_sol ( );
double p13_start ( );
void p13_title ( char *title );
double p14_f ( double x );
double p14_f1 ( double x );
double p14_f2 ( double x );
void p14_interval ( double *a, double *b );
double p14_sol ( );
double p14_start ( );
void p14_title ( char *title );
double r8_add ( double x, double y );
double r8_epsilon ( );
double r8_sign ( double x );
void timestamp ( );
